image: Visual Studio 2017
platform: 
  x64
skip_commits:
  files:
    - '*.md'
    - '.gitignore'
    - '.travis.yml'
matrix:
  fast_finish: true
environment:
  matrix:
    - PLATFORM: x86
      BUILDER: CMake
      GENERATOR: "Visual Studio 15 2017"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - PLATFORM: x64
      BUILDER: CMake
      GENERATOR: "Visual Studio 15 2017 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - PLATFORM: x86
      BUILDER: CMake
      GENERATOR: "Visual Studio 14 2015"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - PLATFORM: x64
      BUILDER: CMake
      GENERATOR: "Visual Studio 14 2015 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
configuration:
  - Debug
  - Release

before_build:
  - set CTEST_OUTPUT_ON_FAILURE=1
  - set ZLIB_VER_DOT=1.2.8
  - ps: appveyor DownloadFile "https://github.com/madler/zlib/archive/v${env:ZLIB_VER_DOT}.zip" -FileName "zlib.zip"
  - 7z x zlib.zip
  - ps: Rename-Item -path "zlib-${env:ZLIB_VER_DOT}" -newName "zlib"
  - cd zlib
  - ps: (Get-Content win32/Makefile.msc).replace('-MD', '-MT') | Set-Content win32/Makefile.msc
  - nmake -f win32/Makefile.msc zlib.lib
  - copy zlib.lib ..
  - cd ..
  - cmake.exe -G "%GENERATOR%" -DCMAKE_BUILD_TYPE=%CONFIGURATION% %APPVEYOR_BUILD_FOLDER%

build_script:
  - cmake --build . --config %CONFIGURATION%

test_script:
  - ctest --output-on-failure -C %CONFIGURATION%
