image: Visual Studio 2017
platform: 
  x64
skip_commits:
  files:
    - '*.md'
    - '.gitignore'
    - '.travis.yml'
matrix:
  fast_finish: true
environment:
  matrix:
    - PLATFORM: x86
      BUILDER: CMake
      GENERATOR: "Visual Studio 15 2017"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - PLATFORM: x64
      BUILDER: CMake
      GENERATOR: "Visual Studio 15 2017 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - PLATFORM: x86
      BUILDER: CMake
      GENERATOR: "Visual Studio 14 2015"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - PLATFORM: x64
      BUILDER: CMake
      GENERATOR: "Visual Studio 14 2015 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
configuration:
  - Debug
  - Release

before_build:
  - set CTEST_OUTPUT_ON_FAILURE=1
  - set PATH=%PATH:C:\Program Files (x86)\Git\bin;=%.
  - git clone https://github.com/katahiromz/zlib
  - cd zlib
  - cmake .
  - cmake --build . --target INSTALL
  - cd ..
  - git clone https://github.com/katahiromz/bzip2_cmake
  - cd bzip2_cmake
  - cmake .
  - cmake --build . --target INSTALL
  - cd ..
  - git clone https://github.com/katahiromz/xz
  - cd xz
  - cmake .
  - cmake --build . --target INSTALL
  - cd ..
  - cmake -G "%GENERATOR%" -DCMAKE_BUILD_TYPE=%CONFIGURATION% %APPVEYOR_BUILD_FOLDER%

build_script:
  - cmake --build . --config %CONFIGURATION%

test_script:
  - ctest --output-on-failure -C %CONFIGURATION%
