image: Visual Studio 2017
platform: 
  x64
skip_commits:
  files:
    - '*.md'
    - '.gitignore'
    - '.travis.yml'
cache: c:\tools\vcpkg\installed\
matrix:
  fast_finish: true
environment:
  matrix:
    - PLATFORM: x86
      BUILDER: CMake
      GENERATOR: "Visual Studio 15 2017"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      MSVC_VER: 15
    - PLATFORM: x64
      BUILDER: CMake
      GENERATOR: "Visual Studio 15 2017 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      MSVC_VER: 15
    - PLATFORM: x86
      BUILDER: CMake
      GENERATOR: "Visual Studio 14 2015"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      MSVC_VER: 14
    - PLATFORM: x64
      BUILDER: CMake
      GENERATOR: "Visual Studio 14 2015 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      MSVC_VER: 14
configuration:
  - Release
install:
  - cd C:\tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
  - cd %APPVEYOR_BUILD_FOLDER%
before_build:
  - cmake --version

  - set CTEST_OUTPUT_ON_FAILURE=1
  - set PATH=%PATH:C:\Program Files (x86)\Git\bin;=%.

  - if %MSVC_VER%==15 if %PLATFORM%==x86 call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
  - if %MSVC_VER%==15 if %PLATFORM%==x64 call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - if %MSVC_VER%==14 if %PLATFORM%==x86 call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
  - if %MSVC_VER%==14 if %PLATFORM%==x64 call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
  - if %MSVC_VER%==14 if %PLATFORM%==x64 call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64

  - if %PLATFORM%==x86 vcpkg install zlib:x86-windows
  - if %PLATFORM%==x64 vcpkg install zlib:x64-windows
  - if %PLATFORM%==x86 vcpkg install bzip2:x86-windows
  - if %PLATFORM%==x64 vcpkg install bzip2:x64-windows
  - if %PLATFORM%==x86 vcpkg install liblzma:x86-windows
  - if %PLATFORM%==x64 vcpkg install liblzma:x64-windows
  - vcpkg integrate install

  - cmake -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -G "%GENERATOR%" -DCMAKE_BUILD_TYPE=%CONFIGURATION% %APPVEYOR_BUILD_FOLDER%

build_script:
  - cmake --build . --config %CONFIGURATION%

test_script:
  - ctest --output-on-failure -C %CONFIGURATION%
